### ISSUE TITLE
[INICIAR SESION]  Icono del "Ojo" no se muestra para encriptar o desencriptar contraseñia

### ISSUE THREAD

**Issue by vcamachotec** [vcamachotec/Sistema-Luzhy-Express#8]
![IconoOjoiniciarsesion](https://github.com/vcamachotec/Sistema-Luzhy-Express/assets/173747817/c8332234-1152-42ab-8ca8-6d7e9462d375)

**Comment by layosis** [comment]
asdkljhaskjdhasjkhd askjd kas djka dkja dkjas dkja dkaj

**Comment by layosis** [comment]
sa dasdasd asd a skdasjdlkasdkas dlaks dja

**Comment by vcamachotec** [comment]
Falta completar

**Comment by vcamachotec** [comment]
abrir issu
